set_property SRC_FILE_INFO {cfile:c:/Users/ethan/Vivado_Projects/basic_i2c/basic_i2c.gen/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc rfile:../../../../../basic_i2c.gen/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/ethan/Vivado_Projects/basic_i2c/basic_i2c.runs/div_gen_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 1000.000 -name aclk [get_ports aclk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U0]
